### ISSUE TITLE
failure finding "self" vessel in signalk server.

### ISSUE THREAD

**Issue by ph1l** [ph1l/python-signalk-client#4]
```
elektron@x61s:~$ pysk -L DEBUG signalk:8080 -i espeak > /tmp/pysk.log

Traceback (most recent call last):
  File "/usr/local/bin/pysk", line 9, in <module>
    load_entry_point('pysk==0.1.0', 'console_scripts', 'pysk')()
  File "build/bdist.linux-x86_64/egg/pysk/pysk.py", line 97, in main
  File "build/bdist.linux-x86_64/egg/pysk/pysk.py", line 37, in call_interface_plugin
  File "build/bdist.linux-x86_64/egg/pysk/interface_espeak.py", line 37, in interface_main
  File "build/bdist.linux-x86_64/egg/signalk_client/data.py", line 133, in get_self
KeyError: 'self'
```

**Comment by ph1l** [comment]
When running the SignlaK/signalk-java server, the server does not provide a `self` property that defines the local vessel:

https://github.com/SignalK/specification/blob/master/schemas/signalk.json#L11
```
  "properties": {
    "self": {
      "type": "string",
      "description": "This holds the key (UUID, MMSI or URL) of this vessel, the actual data is in the vessels array.",
      "example": "urn:mrn:signalk:uuid:6b0e776f-811a-4b35-980e-b93405371bc5"
    },
```

This option is not required, so I need to more gracefully handle this error. However, for the benefit of client devs in the community, publishing this information, if available, would be helpful.

*Related to:* SignalK/signalk-server-java#29

**Comment by ph1l** [comment]
I think my problem here is that the java-server doesn't publish the self property in the rest api.

I start up and load the initial data from the REST API and then fire off a thread to do websocket delta processing. If my background websocket thread hasn't processed the [hello](http://signalk.org/specification/master/streaming_api.html) message, which actually does require a `self` property, I am not guaranteed to have a self property, unless I block on seeing a hello message.
